# Generated by Django 5.2.9 on 2026-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_highlighted',
            field=models.BooleanField(db_index=True, default=False, help_text='Highlighted news (multiple allowed)'),
        ),
    ]
