# Generated by Django 5.2.9 on 2026-01-11 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('designation', models.CharField(blank=True, help_text='Designation or role (e.g. CEO, Client)', max_length=100, null=True)),
                ('company', models.CharField(blank=True, help_text='Company or organization name', max_length=150, null=True)),
                ('message', models.TextField(help_text='Testimonial message/content')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating out of 5', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
