# Generated by Django 5.2.9 on 2026-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='team/profile/'),
        ),
    ]
