# Generated by Django 5.2.9 on 2026-01-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
