# Generated by Django 5.2.9 on 2026-01-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0002_alter_socialplatform_icon_svg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialplatform',
            options={'verbose_name': 'Social Platform', 'verbose_name_plural': 'Social Platforms'},
        ),
    ]
