# Generated by Django 5.2.9 on 2026-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0003_alter_socialplatform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG path only (d attribute)', null=True),
        ),
    ]
