# Generated by Django 5.2.9 on 2026-01-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
