# Generated by Django 5.2.9 on 2026-01-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_remove_project_category'),
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='service_api.service'),
        ),
    ]
